# Generated by Django 3.0.5 on 2020-05-11 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='active',
            new_name='ativo',
        ),
    ]
