# Generated by Django 3.0.5 on 2020-05-11 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200511_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='ativo',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='tipoproduto',
            old_name='name',
            new_name='nome',
        ),
    ]
