# Generated by Django 3.0.5 on 2020-05-11 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200511_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='active',
            new_name='ativo',
        ),
    ]
