# Generated by Django 3.0.5 on 2020-05-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200511_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='texto_longo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
